version: 2
updates:app/src/main/java/com/termux/app/TermuxApplication.java
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    # Prefix all commit messages with "Changed: "
    prefix: "Changed"
